### ISSUE TITLE
RangeError thrown during API client initialization

### ISSUE THREAD

**Issue by EdwardRodr1guez** [clerk/clerk-sdk-flutter#64]
### Steps to reproduce

run example code

### Expected results

idk... homescreen or main screen never shown

### Actual results

AsyncSnapshot<ClerkAuthProvider>(ConnectionState.done, null, RangeError (end): Invalid value: Only valid value is 1: 0, #0      RangeError.checkValidRange (dart:core/errors.dart:365:9)

AsyncSnapshot<ClerkAuthProvider>(ConnectionState.done, null, RangeError (end): Invalid value: Only valid value is 1: 0, #0      RangeError.checkValidRange (dart:core/errors.dart:365:9)
I/flutter (26316): #1      List.sublist (dart:core-patch/growable_array.dart:84:38)
I/flutter (26316): #2      KeyParser.bytesFromPEM (package:dart_jsonwebtoken/src/key_parser.dart:277:30)
I/flutter (26316): #3      KeyParser.rsaPublicKeyFromPEM (package:dart_jsonwebtoken/src/key_parser.dart:82:17)
I/flutter (26316): #4      new RSAPublicKey (package:dart_jsonwebtoken/src/keys.dart:40:21)
I/flutter (26316): #5      TokenCache.initialize (package:clerk_auth/src/clerk_api/token_cache.dart:62:15)
I/flutter (26316): #6      Api.initialize (package:clerk_auth/src/clerk_api/api.dart:72:23)
I/flutter (26316): #7      Auth.initialize (package:clerk_auth/src/clerk_auth/auth.dart:85:16)
I/flutter (26316): #8      ClerkAuthProvider.create (package:clerk_flutter/src/widgets/control/clerk_auth_provider.dart:42:20)
I/flutter (26316): #9      _ClerkAuthState.initState (package:clerk_flutter/src/widgets/control/clerk_auth.dart:98:25)
I/flutter (26316): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.da

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by shinyford** [comment]
I think this is a manifestation of a problem that has recently been fixed, and will soon be merged in. I'll comment again when that's been done, and ask you to check again. Cheers!
